config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :users do
    get '', to: 'connections#index'

    get 'my_followers', to: 'connections#followers', as: 'my_followers'
    get 'my_follows', to: 'connections#follows', as: 'my_follows'
  end
  get 'users/:id', to: 'users/connections#show', as: 'user'

  post 'follow/:id', to: 'follows#create', as: 'follow'

  delete 'unfollow/:id', to: 'follows#destroy', as: 'unfollow'

  get 'what_spot', to: 'pages#what_spot'

  root to: 'pages#home'

  get 'map', to: 'maps#show'

  resources :spots, only: [:show, :index, :create, :destroy, :new ] do
    resources :favourites, only: :create
    resources :stories, only: [:index, :new, :show, :create]
  end
  resources :favourites, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord

  # Associations
  has_many :stories, dependent: :destroy
  belongs_to :category
  has_many :photos, as: :photoable
  has_many :favourites
  has_many :questions, through: :category
  # Validations
  validates :name, presence: true
  validates :location, presence: true
  validates :category, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_name_location_and_category,
  against: [ :name, :location ],
  associated_against: {
      category: [ :name ]
    },
  using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  # include PgSearch::Model



  def favourited(user)
    Favourite.where("spot_id = #{id} and user_id = #{user.id}")
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  require "open-uri"

  def index
    @spots = following_only
    @spots = @spots.geocoded
    if params[:query].present?
      @spots = @spots.search_by_name_location_and_category(params[:query])
    end

    @spots = @spots.near(params[:query_location], 5) if params[:query_location].present? && !@spots.empty?
    # spots.near(location search)
    @markers = @spots.map do |spot| {
      icon: "https://res.cloudinary.com/daqhmzr2j/image/upload/v1592440394/1946401_aezpko.png",
      lat: spot.latitude,
      lng: spot.longitude
      }
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @stories = @spot.stories
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @user = current_user
    # @spot.photo = spot_params[:photos]
    spot_photo = Photo.new
    if (params[:no_model_fields][:photo_url]).empty?
      file = URI.open("https://www.travelmarvel.com.au/-/media/apt-responsive-website/miscellaneous/hero-panel-12-5/generic-12-5/hc-a-gen-map-travel-destinations-419995780-s-12-5.jpg?useCustomFunctions=1&rw=2280&w=1900&h=950&cropX=304&cropY=0")
    else
      file = URI.open(params[:no_model_fields][:photo_url])
    end
    spot_photo.file.attach(io: file, filename: "#{@spot.name}", content_type: 'image/jpg')
    @spot.photos = [spot_photo]
    if @spot.save
      redirect_to new_spot_story_path(@spot)
    else
      render 'new'
    end
  end
    # @spot = Spot.new(spot_params)
    # @user = current_user
    # file = URI.open(spot_params[:photos])
    # @spot.photo.attach(io: file, filename: "#{spot.name}", content_type: 'image/png')
    #   if @spot.save
    #     redirect_to spot_path(@spot)
    #   else
    #     render 'new'
    #   end

  def destroy
    @spot.destroy
    redirect_to spots_path
  end

  private

  def spot_params
    params.require(:spot).permit(:location, :name, :category_id)
  end

  # returns spots with associated stories created by users the current user is following
  def following_only
    Spot.includes(:stories).where(stories: { user_id: current_user.leaders_ids + [current_user.id] })
  end
end

app/views/spots/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% spot.photos.each_with_index do |photo, index| %>
      <% if index.zero? %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>
        <%= cl_image_tag photo.file.key, height: 300, width: 300, crop: :fill, class: "d-block w-100" %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/spots/_info_window.html.erb
<div class="container map-info-window">
  <div class="d-flex justify-content-between">
  <%= render 'shared/favourite_button', spot: spot %>
  </div>
  <%= link_to spot.name, spot_path(spot) %>

  <p><%= spot.location %></p>
  <p><%= spot.category.name %></p>
</div>

app/views/spots/_search_bar.html.erb
 <%= form_tag spots_path, class: "d-flex", method: :get do %>
    <%= text_field_tag :query,
      params[:query_attributes],
      class: "form-control spots-search",
      placeholder: "Search by name, location or category"
    %>
    <%= submit_tag "Search", class: "hide-me btn btn-primary waves-light waves-effect" %>
  <% end %>

app/views/spots/_show_modal.html.erb
<div class="spot-page">
  <div class="spot-banner mb-3">
    <div class="button-bar">
      <!-- <div class="back-button">
        <%#= link_to spots_path do %>
        <i class="fa fa-arrow-left" style="font-size:28px"></i>
        <#% end %>
      </div> -->
      <%= render 'shared/favourite_button', spot: spot %>
    </div>

    <div class="modal-info spot-info p-3 d-flex flex-wrap flex-column">
      <h5 class=""><%= @spot.name  %></h5>
      <p class=""><%= @spot.location  %> </p>
      <p><%= @spot.category.name %></p>
    </div>

    <div class="owl-carousel">
      <% @spot.photos.each do |photo| %>
      <%= cl_image_tag photo.file.key, height: 300, width: 375, crop: :fill, class: "d-block w-100" %>
      <% end %>
    </div>
  </div>
</div>


<div class="accordion" id="accordionStories">
  <% @stories.each_with_index do |story, index| %>
  <div class="modal-card">
    <button class="card-button" type="button" data-toggle="collapse" data-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">

      <div class="card-header " id="heading<%= index %>" style="position: relative;">

        <div class="d-flex">
          <div class="justify-content-start d-flex">
          <%= link_to user_path(story.user) do %>
          <%= cl_image_tag story.user.photo.file.key, height: 100, width: 100, crop: :fill, class: "avatar-large", alt: "avatar-large" %>
          <% end %>

          <div class="story-title mt-2 ml-3">
            <h4><%= story.user.first_name %></h4>
            <p class="modal-story-content"> "<%= story.content %>"</p>
          </div>
        </div>
      </div>
    </button>

    <div id="collapse<%= index %>" class="collapse" aria-labelledby="heading<%= index %>" data-parent="#accordionStories">
      <div class="card-body">
        <p style="color: transparent;"><%= story.content %></p>
        <%= cl_image_tag story.photos.first.file.key, height: 300, width: 300, crop: :fill, class: "d-block w-100 story-photo" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<!--  -->
  <div class="add-story-button-container">
    <div class="d-flex justify-content-end m-2 story-button-container">
      <%= link_to "+", new_spot_story_path(@spot), class: "add-story-button" %>
    </div>
  </div>
<!--  -->
<!-- <div class="add-story-button">
  <div class="d-flex justify-content-end m-2">
    <%#= link_to new_spot_story_path(@spot) do %>
    <svg class="bi bi-plus-circle" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
      <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
      <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    </svg>
    <#% end %>
  </div>
</div> -->

app/views/spots/index.html.erb
<div class="mt-5 mb-3 container map-container">
  <div class="add-spot-button-container">
    <div class="d-flex justify-content-end m-2 spot-button-container">
      <%= link_to "+", new_spot_path, class: "add-spot-button" %>
    </div>
  </div>
    <%= render 'search_bar' %>
</div>
<div id="wrapper">
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>">
  </div>
  <div class="horizontal-scrollable" id="over_map">
    <div class="horizontal-row px-5 js-map-carousel">
      <% @spots.each do |spot| %>
        <div class= "card mt-3 carousel-card-wrapper">
          <%= link_to "", spot_path(spot), :remote => true, class: "full-card-link" %>
          <%= render 'shared/favourite_button', spot: spot %>
          <div class="spot-banner">
            <div class="button-bar">
            </div>
          </div>
          <div class="index-image">
            <%= link_to spot_path(spot), :remote => true do %>
                <% if spot.photos.first %>
                <%=  cl_image_tag spot.photos.first.file.key, height: 350, width: 350, crop: :fill, class: "card-img-top waves-light waves-effect"%>
            <% end %>
          <% end %>
          </div>
          <div class="card-description p-3 map-card">
            <h5><%= spot.name%></h5>
              <p class="location"><%= spot.location %></p>
              <p class="category"><%= spot.category.name %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal from here -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fa fa-times modal-close"></i></span>
        </button>

       <!--  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="close fa fa-times"></i></span>
        </button> -->
      </div>
      <div class="modal-body js-spot-show">
        <!-- Called show.js.erb using class js-spot-show above -->
      </div>
    </div>
  </div>
</div>

app/views/spots/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm mt-5">
      <%= simple_form_for @spot do |f| %>
      <input type="text" class="js-auto-complete"/>
      <%= f.input :place_id, input_html: { class: "js-place-id" } , :label => false, as: "hidden" %>
      <%= f.input :name, :label => false, input_html: { class: "js-place-name" }, as: "hidden" %>
      <%= f.input :location, :label => "Location:", input_html: { class: "js-place-address" } %>
      <%= simple_fields_for :no_model_fields do |n| %>
      <%= n.input :photo_url, :label => false, input_html: { class: "js-place-photo" }, as: "hidden" %>
      <% end %>
      <%= f.association :category, :label => "What category is this spot?" %>
      <%= f.button :submit, class: "btn btn-primary waves-light waves-effect" %>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/show.html.erb
<!-- NOTE: We Don't Use This View Any More -->
<!-- Because We Use Bootstrap Modal for Spot Show -->

<div class="spot-page">
  <div class="spot-banner mb-3 mt-5">

    <div class="button-bar">
      <div class="back-button">
        <%= link_to spots_path do %>
        <i class="fa fa-arrow-left" style="font-size:28px"></i>
        <% end %>
      </div>
      <%= render 'shared/favourite_button', spot: @spot %>
    </div>

    <div class="spot-info">
      <h5 class="card-title spot-title"><%= @spot.name  %></h5>
      <p class="card-text spot-address"><%= @spot.location  %> </p>
    </div>

    <div class="owl-carousel">
      <% @spot.photos.each do |photo| %>
      <%= cl_image_tag photo.file.key, height: 300, width: 300, crop: :fill, class: "d-block w-100" %>
      <% end %>
    </div>
  </div>
</div>


<div class="accordion" id="accordionStories">
  <% @stories.each_with_index do |story, index| %>
  <div class="card">
    <button class="btn btn-link card-button" type="button" data-toggle="collapse" data-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">

      <div class="card-header" id="heading<%= index %>">

        <div class="d-flex justify-content-around">
          <%= link_to user_path(story.user) do %>
          <%= cl_image_tag story.user.photo.file.key, height: 100, width: 100, crop: :fill, class: "avatar-large", alt: "avatar-large" %>
          <% end %>
          <div class="mt-3">
            <h4><%= story.user.username %>'s story</h4>
          </div>
        </div>
      </div>
    </button>

    <div id="collapse<%= index %>" class="collapse" aria-labelledby="heading<%= index %>" data-parent="#accordionStories">
      <div class="card-body">
        <em><%= story.content %></em>
      </div>
    </div>

  </div>
  <% end %>
</div>

<div class="add-story-button">
  <div class="d-flex justify-content-end m-2">
    <%= link_to new_spot_story_path(@spot) do %>
    <div class="fas fa-plus-circle waves-light waves-effect" style="font-size:70px;">
    </div>
    <% end %>
  </div>
</div>

app/views/spots/show.js.erb
$('#staticBackdrop').modal('toggle')
document.querySelector(".js-spot-show").innerHTML = "<%= escape_javascript(render 'spots/show_modal', spot: @spot) %>";
window.initOwlCarousel();
window.initFavouriteButton();