config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :users do
    get '', to: 'connections#index'

    get 'my_followers', to: 'connections#followers', as: 'my_followers'
    get 'my_follows', to: 'connections#follows', as: 'my_follows'
  end
  get 'users/:id', to: 'users/connections#show', as: 'user'

  post 'follow/:id', to: 'follows#create', as: 'follow'

  delete 'unfollow/:id', to: 'follows#destroy', as: 'unfollow'

  get 'what_spot', to: 'pages#what_spot'

  root to: 'pages#home'

  get 'map', to: 'maps#show'

  resources :spots, only: [:show, :index, :create, :destroy, :new ] do
    resources :favourites, only: :create
    resources :stories, only: [:index, :new, :show, :create]
  end
  resources :favourites, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% photoable.photos.each_with_index do |photo, index| %>
      <% if index.zero? %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>
        <%= cl_image_tag photo.file.key, height: 300, width: 300, crop: :fill, class: "d-block w-100" %>
      </div>
    <% end %>
  </div>
  <% if photoable.photos.count > 1 %>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <% end %>
</div>
</div>

app/views/shared/_favourite_button.html.erb
<% favourite = spot.favourited(current_user) %>
<% if favourite.empty? %>
  <i class="far fa-heart fa-2x m-1 js-favourite-btn fav-btn" data-favstate = "not favourited" data-spot_id= <%= spot.id %> ></i>
<% else %>
<i class="fas fa-heart fa-2x m-1 js-favourite-btn fav-btn" data-favstate = "favourited" data-favourite_id= <%= favourite.first.id %> data-spot_id= <%= spot.id %> ></i>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_follow_button.html.erb
<% if user != current_user %>
  <% follow = current_user.following(user) %>
  <% if follow.empty? %>
      <i class="far fa-plus-square fa-2x m-1 js-follow-btn" data-followstate = "not following" data-user_id= <%= user.id %> ></i>
  <% else %>
      <i class="fas fa-minus-square fa-2x m-1 js-follow-btn" data-followstate = "following" data-follow_id= <%= follow.first.id %> data-user_id=<%= user.id %> ></i>
  <% end %>
<% end %>

app/views/shared/_follow_button_new.html.erb
<% if user != current_user %>
  <% follow = current_user.following(user) %>
  <% if follow.empty? %>
      <i class="far fa-plus-square fa-2x m-1 js-follow-btn" data-followstate = "not following" data-user_id= <%= user.id %> ></i>
  <% else %>
      <i class="fas fa-minus-square fa-2x m-1 js-follow-btn" data-followstate = "following" data-follow_id= <%= follow.first.id %> data-user_id=<%= user.id %> ></i>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer mt-4 font-small unique-color-dark">

  <div style="background-color: #6CC8E5;">
    <div class="container">

      <div class="row py-4 d-flex align-items-center">

        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>

          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>

          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
      </div>
    </div>
  </div>

<!--   <div class="container text-center text-md-left mt-5">
    <div class="row mt-3">
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <h6 class="text-uppercase font-weight-bold">WhatSpot</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Whatspot lets you create lists of your favourite places and share them with your friends.</p>

      </div> -->

   <!--    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <%= link_to "Your Account", "" %>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>
      </div> -->

<!--       <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i>Melbourne, Australia</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 61 111 111 111</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 61 111 111 111</p>
     </div> -->

    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-spotty">

  <%= link_to "<h1>What's The Spot?</h1>".html_safe, root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Bucket List", favourites_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Spots", spots_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Add a spot", new_spot_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Find other Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: white;" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Spots", spots_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar_menu.html.erb
<div class="menu-top-bar">What's The Spot?</div>
<span class="menu_toggle js-menu-toggle">
  <i class="menu_open fa fa-bars fa-lg"></i>
  <i class="menu_close fa fa-times fa-lg"></i>
</span>
<ul class="menu_items">
  <% if user_signed_in? %>
    <li>
      <%= link_to "Spots", spots_path %>
    </li>
    <li>
      <%= link_to "Connect", users_path %>
    </li>
    <li>
      <%= link_to "Bucket List", favourites_path %>
    </li>
    <li>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
      <%= link_to "Spots", spots_path %>
    </li>
    <li>
      <%= link_to "Log in", new_user_session_path, style: "color: white;" %>
    </li>
<% end %>
</ul>