config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :users do
    get '', to: 'connections#index'

    get 'my_followers', to: 'connections#followers', as: 'my_followers'
    get 'my_follows', to: 'connections#follows', as: 'my_follows'
  end
  get 'users/:id', to: 'users/connections#show', as: 'user'

  post 'follow/:id', to: 'follows#create', as: 'follow'

  delete 'unfollow/:id', to: 'follows#destroy', as: 'unfollow'

  get 'what_spot', to: 'pages#what_spot'

  root to: 'pages#home'

  get 'map', to: 'maps#show'

  resources :spots, only: [:show, :index, :create, :destroy, :new ] do
    resources :favourites, only: :create
    resources :stories, only: [:index, :new, :show, :create]
  end
  resources :favourites, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  include Comparable
  # Associations
  belongs_to :user
  belongs_to :spot
  belongs_to :question
  has_many :photos, as: :photoable
  # accepts_nested_attributes_for :photos

  # Validations
  validates :user, presence: true
  validates :spot, presence: true
  validates :content, presence: true

  # Will sort active record relation of stories with stories from users
  # the current user is following sorted to the beginning
  # def self.sort_by_following(stories, user)
  #   sorted = stories.sort
  #   return sorted
  # end

  def <=>(other)
    current_user.following(user).size <=> current_user.following(other.user).size
    # user.id <=> other.user.id
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def show
    @spot = Spot.find(params[:spot_id])
    @story = Story.find(params[:id])
  end

  def new
    @spot = Spot.find(params[:spot_id])
    @story = Story.new
    # 3.times do
    @photo = @story.photos.build
    # end
  end

  def create
    @spot = Spot.find(params[:spot_id])
    @story = Story.new(story_params.except(:photos_attributes, :question))
    @story.spot = @spot
    @story.user = current_user
    @story.question = Question.find(story_params[:question])
    if  @story.save
      multiple_photos(params[:story][:photos], @story)
      # @photo = Photo.new
      # @photo.file.attach(story_params[:photo][:file])
      # @photo.photoable = @story
      # @photo.save!
      redirect_to spots_path
    else
      render 'new'
    end
  end
  # params[:story][:photos_attributes]["0"][:file]
  def multiple_photos(story_params, story)
    story_params[:file].each do |image|
      @photo = Photo.new
      @photo.file.attach(image)
      @photo.photoable = story
      @photo.save!
    end
  end

  def story_params
    params.require(:story).permit(:content, :question, photos_attributes: [:file])
  end
end

app/views/stories/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm mt-5">
      <div class="add">
        <!-- <div class="back-button">
          <%#= link_to spots_path do %>
          <i class="fa fa-arrow-left" style="font-size:28px"></i>
          <#% end %> -->
        </div>
          <%= simple_form_for [@spot, @story] do |f| %>
            <%= f.simple_fields_for :photos do |m| %>
              <%= m.input :file, as: :file, :input_html => { multiple: true }, name: "file" %>
            <% end %>
            <%= f.input :question, required: true,
                      as: :select,
                      collection: @spot.questions,
                      label_method: :content,
                      value_method: :id,
                      input_html: { class: 'select2' }
                        %>
            <%= f.input :content, label: "Answer" %>
            <%= f.button :submit, class: "btn btn-primary waves-light waves-effect" %>
          <% end %>
      </div>
    </div>
</div>


<!-- NOTE: Just Refferences bellow -->
  <%#= f.input :qol_selection, :as => :select, :collection => QuestionModel.qol_selections.keys.to_a
 %>

app/views/stories/show.html.erb
<!-- NOTE: We Don't Use This View Any More -->
<!-- Because We Use Collapse Function For Story Show -->

<div class="container">
  <div class="row">

    <div class="story">
      <div class="story-cover flex-column" style="background-image: url(<%= render 'shared/carousel', photoable: @story %>)">
        <div class="col d-flex justify-content-between px-3 mt-3">
          <div>
            <%= link_to "Back", spot_path(@spot), class: "btn btn-dark mt-3" %>
          </div>
          <div>
            <%= render 'shared/favourite_button', spot: @spot %>
          </div>
        </div>
      </div>
      <div class="col-sm d-flex justify-content-center">
        <h3><%= @story.spot.name %></h3>
      </div>

      <div class="story-content-scroller">
        <div class="story-content">
          <div class="col-sm d-flex justify-content-between px-3 mt-3">
            <div>
              <h5><%= link_to @spot.location, "https://www.google.com/maps", target: :_blank %>
               / <%= @spot.category.name %></h5>
             </div>

             <div>
              <p><%= @spot.favourites.count %> like</p>
            </div>
          </div>

          <div class="col-sm border-bottom px-3">
          </div>
          <div class="col-sm d-flex justify-content-between px-3 mt-3" style="">
            <h5><%= "#{@spot.category.question}?" %></h5>
          </div>
          <div class="col-sm d-flex justify-content-between px-3 mt-3">
            <h5><%= @story.content %></h5>
          </div>
          <div class="col-sm d-flex justify-content-end border-bottom px-3 mt-3">
            <h5>
              <%= current_user.first_name %>
            </h5>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Back", spot_path(@spot), class: "btn btn-dark mt-5 mb-5 waves-light waves-effect" %>
</div>
</div>